"""Cross-verification tests — verify ciphertrust against python-rsa.

These tests generate keys/signatures with python-rsa and verify with ciphertrust
(and vice versa). Skipped when python-rsa is not installed.
"""

from __future__ import annotations

import pytest

import ciphertrust

try:
    import rsa  # type: ignore[import-untyped]
    HAS_RSA = True
except ImportError:
    HAS_RSA = False

pytestmark = pytest.mark.skipif(not HAS_RSA, reason="python-rsa not installed")


class TestKeyInterop:
    """Keys generated by one library can be loaded by the other."""

    def test_ciphertrust_pubkey_loadable_by_rsa(self) -> None:
        pub, _priv = ciphertrust.newkeys(512)
        pem = pub.save_pkcs1("PEM")
        rsa_pub = rsa.PublicKey.load_pkcs1(pem)
        assert rsa_pub.n == pub.n
        assert rsa_pub.e == pub.e

    def test_rsa_pubkey_loadable_by_ciphertrust(self) -> None:
        pub, _priv = rsa.newkeys(512)
        pem = pub.save_pkcs1("PEM")
        arc_pub = ciphertrust.PublicKey.load_pkcs1(pem)
        assert arc_pub.n == pub.n
        assert arc_pub.e == pub.e

    def test_ciphertrust_privkey_loadable_by_rsa(self) -> None:
        _pub, priv = ciphertrust.newkeys(512)
        pem = priv.save_pkcs1("PEM")
        rsa_priv = rsa.PrivateKey.load_pkcs1(pem)
        assert rsa_priv.n == priv.n
        assert rsa_priv.d == priv.d

    def test_rsa_privkey_loadable_by_ciphertrust(self) -> None:
        _pub, priv = rsa.newkeys(512)
        pem = priv.save_pkcs1("PEM")
        arc_priv = ciphertrust.PrivateKey.load_pkcs1(pem)
        assert arc_priv.n == priv.n
        assert arc_priv.d == priv.d

    def test_ciphertrust_pubkey_der_loadable_by_rsa(self) -> None:
        pub, _priv = ciphertrust.newkeys(512)
        der = pub.save_pkcs1("DER")
        rsa_pub = rsa.PublicKey.load_pkcs1(der, "DER")
        assert rsa_pub.n == pub.n

    def test_rsa_pubkey_der_loadable_by_ciphertrust(self) -> None:
        pub, _priv = rsa.newkeys(512)
        der = pub.save_pkcs1("DER")
        arc_pub = ciphertrust.PublicKey.load_pkcs1(der, "DER")
        assert arc_pub.n == pub.n


class TestEncryptDecryptInterop:
    """Ciphertext from one library can be decrypted by the other."""

    def test_ciphertrust_encrypt_rsa_decrypt(self) -> None:
        pub, priv = rsa.newkeys(512)
        # Load the rsa key into ciphertrust
        arc_pub = ciphertrust.PublicKey.load_pkcs1(pub.save_pkcs1("PEM"))
        ct = ciphertrust.encrypt(b"hello from ciphertrust", arc_pub)
        assert rsa.decrypt(ct, priv) == b"hello from ciphertrust"

    def test_rsa_encrypt_ciphertrust_decrypt(self) -> None:
        pub, priv = rsa.newkeys(512)
        arc_priv = ciphertrust.PrivateKey.load_pkcs1(priv.save_pkcs1("PEM"))
        ct = rsa.encrypt(b"hello from rsa", pub)
        assert ciphertrust.decrypt(ct, arc_priv) == b"hello from rsa"


class TestSignVerifyInterop:
    """Signatures from one library can be verified by the other."""

    def test_ciphertrust_sign_rsa_verify(self) -> None:
        pub, priv = ciphertrust.newkeys(512)
        rsa_pub = rsa.PublicKey.load_pkcs1(pub.save_pkcs1("PEM"))
        sig = ciphertrust.sign(b"test data", priv, "SHA-256")
        assert rsa.verify(b"test data", sig, rsa_pub) == "SHA-256"

    def test_rsa_sign_ciphertrust_verify(self) -> None:
        pub, priv = rsa.newkeys(512)
        arc_pub = ciphertrust.PublicKey.load_pkcs1(pub.save_pkcs1("PEM"))
        sig = rsa.sign(b"test data", priv, "SHA-256")
        assert ciphertrust.verify(b"test data", sig, arc_pub) == "SHA-256"

    def test_ciphertrust_sign_rsa_verify_sha1(self) -> None:
        pub, priv = ciphertrust.newkeys(512)
        rsa_pub = rsa.PublicKey.load_pkcs1(pub.save_pkcs1("PEM"))
        sig = ciphertrust.sign(b"sha1 test", priv, "SHA-1")
        assert rsa.verify(b"sha1 test", sig, rsa_pub) == "SHA-1"

    def test_rsa_sign_ciphertrust_verify_sha1(self) -> None:
        pub, priv = rsa.newkeys(512)
        arc_pub = ciphertrust.PublicKey.load_pkcs1(pub.save_pkcs1("PEM"))
        sig = rsa.sign(b"sha1 test", priv, "SHA-1")
        assert ciphertrust.verify(b"sha1 test", sig, arc_pub) == "SHA-1"

    def test_ciphertrust_sign_rsa_verify_md5(self) -> None:
        pub, priv = ciphertrust.newkeys(512)
        rsa_pub = rsa.PublicKey.load_pkcs1(pub.save_pkcs1("PEM"))
        sig = ciphertrust.sign(b"md5 test", priv, "MD5")
        assert rsa.verify(b"md5 test", sig, rsa_pub) == "MD5"

    def test_rsa_sign_ciphertrust_verify_md5(self) -> None:
        pub, priv = rsa.newkeys(512)
        arc_pub = ciphertrust.PublicKey.load_pkcs1(pub.save_pkcs1("PEM"))
        sig = rsa.sign(b"md5 test", priv, "MD5")
        assert ciphertrust.verify(b"md5 test", sig, arc_pub) == "MD5"
